### ISSUE TITLE
Unfortunately, the first launch of the plugin did not work correctly.

### ISSUE THREAD

**Issue by Dudaevskiy** [pamtbaau/grav-plugin-labeltree#1]
Very grateful for your time, work and attention to my problem. I am very pleasantly surprised by your quick response and lightning-fast writing of the plugin (and in fact already the second one) for me.

I rarely meet such kind and sympathetic people on the Internet, I just really respect your time and you for your work and responsiveness. Thanks again!

I followed the link:

[https://github.com/pamtbaau/grav-plugin-labeltree](https://github.com/pamtbaau/grav-plugin-labeltree)

and uploaded the plugin to the site in accordance with the instructions you specified.

I put the code in the site widget (because the include insert didn&rsquo;t work for some reason):

    {% macro recurseTree (tree, labels, blog)%}
    <ul>
        {% for label in tree.children%}
            <li> <a href = / blog / labels: {{labels == ''? label.name: labels ~ ',' ~ label.name}}> {{label.name}} </a>
                {% if label.children%}
                   {{_self.recurseTree (label, labels == ''? label .name: labels ~ ',' ~ label.name, blog)}}
                {% endif%}
            </ li>
        {% endfor%}
    </ ul>
    {% endmacro%}

    {% set labelTree = labeltree.getLabelTree () %}
    {% if count (labelTree.children)> 0%}
        {{_self.recurseTree (labelTree, '', blog)}}
    {% endif%}
    <hr>

I also replaced this part of the code:

    <li> <a href = {{blog.url}} / labels: {{labels == ''?

For this:

    <li> <a href = / blog / labels: {{labels == ''?

Because with your version of the blog slug it was not displayed, I think it is not significant, but I decided to write about it.

On one of the blog pages, I added the lines you specified (at the very top of the .md page):

    labels:
    - Label-1
        - Label-11
    - Label-2
        - Label-22

After that, the widget appears on the site:

![|269x74](/uploads/getgrav/original/2X/c/cb804c35f04af63c31202de2e3851243005da049.png)

I wasexcited sothat I thought that everything has already worked, but unfortunately when you go to the link, let's say this:

https://techblog.sdstudio.top/blog/labels:Label-1

Content filtering did not occur on the blog, that is, in fact, the page just reloaded. You can now look at the link click as I left your plugin in active mode on the site.

I also found that there is an error in the formation of sub links:

    <ul>
	<li>
		<a href="/blog/labels:Label-1" -="" label-11="> Label-1 - Label- 11 </a>
	</ li>
	<li>
		<a href="/blog/labels:Label-2" -="" label-22="> Label-2 - Label-22 </a>
	</ li>
    </ ul>

Thank you again very much for your work, if we manage to test and configure the plugin, I am sure it will solve the headache of a huge number of Grav users. And do not underestimate your decision, I'm more than sure that this plugin (in the future) should go with the default Grav.

Thank you again.

PS I really hope that the developers of Grav will pay attention to this topic, I am not the first who faced the impossibility of the &ldquo;NORMAL&rdquo; implementation of taxonomies in this forum.

**Comment by pamtbaau** [comment]
Thanks for the feedback. I fixed two issues.

1. **Yaml syntax in frontmatter**:
I noticed a Yaml syntax error in my README.md in the layout of frontmatter. The labels should be defined as:
   ```
   ---
   labels:
       - Label-1:          <-- Colon was missing
           - Label-11
       - Label-2:          <-- Colon was missing
           - Label-22
   ---
   ``` 
1. **Missing quotes in labeltree.html.twig**:
Also, I fixed the omission of quotes surrounding the value of 'href' in the anchors. The browser is forgiving though...

   Note: Quotes are also missing in your adapted code.

**'blog.slug' value**:
I have tested the code using Quark with the 'Blog Site' skeleton. The template 'labeltree.html.twig' is added to '/user/themes/quark/templates/partials/sidebar.html.twig' as shown in the README.md.
In this setup, the variable 'blog' is known in 'labeltree.html.twig' and the correct slug is generated.
Have a look at your own setup. Maybe 'blog' is not defined as in the Quark theme and you might try replacing 'blog' by 'page'.
