### ISSUE TITLE
Everything is displayed correctly but the content is not filtered on the blog page.

### ISSUE THREAD

**Issue by Dudaevskiy** [pamtbaau/grav-plugin-labeltree#3]
Everything is displayed correctly, but the content is not filtered on the blog page, that is, half a click on the link:
https://techblog.sdstudio.top/blog/labels:Label-1,Label-11
It still displays the blog page as before, without filtering the desired entries.

**Comment by pamtbaau** [comment]
Did you make the following required changes as mentioned in the README?

To filter the pages based on the selected label hierarchy, the following should be changed in 'blog.html.twig' in theme Quark:
```
{% set collection = page.collection() %}
   - replace by -
{% set collection = labeltree.getPages(uri.param('labels')) %}
```
