### ISSUE TITLE
Pagination on the pages displayed by the plugin

### ISSUE THREAD

**Issue by Dudaevskiy** [pamtbaau/grav-plugin-labeltree#5]
Hello, the plugin works fine. But not how I can not force it to work with pagination https://github.com/getgrav/grav-plugin-pagination. at the moment all blog entries are displayed in full page as an example:
https://techblog.sdstudio.top/blog/labels:WordPress
. Please tell me how I can sign the pagination to be displayed for the breakdown of content that displays the plugin. thank

**Comment by pamtbaau** [comment]
You are right. It is not playing nicely together with pagination, because pagination knows nothing about the  collection created by `labelTree.getPages()`.

I have created a new version in branche 'pagination'. Would you mind [downloading that version](https://github.com/pamtbaau/grav-plugin-labeltree/tree/pagination) and test it in a test environment?

**Comment by Dudaevskiy** [comment]
Thank you very much, everything worked out. Pagination works as needed.

**Comment by pamtbaau** [comment]
If you are satisfied, can I merge the branch 'pagination' into branch 'master'?

**Comment by Dudaevskiy** [comment]
Yes of course. Thank you very much

**Comment by Dudaevskiy** [comment]
Strange, therefore, as the game ceased to work:
https://techblog.sdstudio.top/blog/labels :%D0%9F%D0%B5%D1%80%D0%B5%D0%B2%D0BB%D0%B4%D1%8B % B3% D0% BE% D0% B4% D0% BD% D1% 8B% D1% 85% 20% D0% BF% D0% BE% D1% 81% D1% 82% D0% BE% D0% B2
Although previously worked as needed

**Comment by Dudaevskiy** [comment]
https://goo.gl/UPyWRA

**Comment by pamtbaau** [comment]
Hm, there are spaces in the label... Are your sure this was working in the previous version? Would you mind testing that?

**Comment by Dudaevskiy** [comment]
> Поэтому странно, что игра перестала работать: 
> [https://techblog.sdstudio.top/blog/labels:%](https://techblog.sdstudio.top/blog/labels) D0% 9F% D0% B5% D1% 80% D0% B5% D0% B2% D0BB% D0% B4% D1% 8B% B3% D0% BE% D0% B4% D0% BD% D1% 8B% D1% 85% 20% D0% BF% D0% BE% D1% 81% D1% 82% D0% BE% D0% B2, 
> хотя ранее работал по мере необходимости

**Comment by Dudaevskiy** [comment]
> Hm, there are spaces in the label... Are your sure this was working in the previous version? Would you mind testing that?

This rubric worked exactly

**Comment by Dudaevskiy** [comment]
https://techblog.sdstudio.top/blog/labels:%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B%20%D0%B4%D0%BB%D1%8F%20Windows

Here, too, there are gaps;

**Comment by Dudaevskiy** [comment]
Can I set a rule to display the link depending on the parent folder of the page?

**Comment by pamtbaau** [comment]
I did a little test by changing the definition of the collection for the blog.

When I have the following file-structure:
```
/pages/
   /01.blog/
      blog.md
      /a-blog-item
         item.md
      /another-blog-item
         item.md
   /02.other/
      default.md
   /03.more/
      /page1/
          default.md
      /page2/
          default.md
```
And a collection defined in 'blog.md' like:
```
content:
    items:
        - '@self.children'
        - '@page.self': '/other'
        - '@page.descendants': '/more'
```
This will show pages 'other', 'page1' and 'page2' in the list of blog items.

**Comment by Dudaevskiy** [comment]
> Я сделал небольшой тест, изменив определение коллекции для блога.
> 
> Когда у меня есть следующая файловая структура:
> 
> ```
> /pages/
>    /01.blog/
>       blog.md
>       /a-blog-item
>          item.md
>       /another-blog-item
>          item.md
>    /02.other/
>       default.md
>    /03.more/
>       /page1/
>           default.md
>       /page2/
>           default.md
> ```
> И коллекция, определенная в blog.md, например:
> 
> ```
> content:
>     items:
>         - '@self.children'
>         - '@page.self': '/other'
>         - '@page.descendants': '/more'
> ```
> Это покажет страницы «прочее», «страница1» и «страница2» в списке элементов блога.
> 
> Дополнительные параметры для определения коллекций см. В [документах по коллекциям](https://learn.getgrav.org/content/collections) .

Fine! I did it all, thank you very much.

**Comment by pamtbaau** [comment]
I will leave the issue open until you don't find any error anymore... ;-)
